language: node_js

cache:
  yarn: true
  directories:
    - node_modules
    - "$HOME/.cache"

before_install:
  - npm install -g yarn

install:
  - yarn --silent

script:
  - yarn run lint
  - yarn run prettier

before_deploy:
  - yarn run prepare

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    branch: master
    tags: true
